all:
  children:
    test_hosts:
      hosts:
        local-test-node:
          ansible_host: host.docker.internal
          ansible_port: 2222
          # never use this config for any other host expect localhost
          ansible_ssh_pass: ansible
          ansible_ssh_args: '-C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no'
